### ISSUE TITLE
Chat - Сверстать UI компоненты чата Vol.1

### ISSUE THREAD

**Issue by AlekseyShaydullin** [AlekseyShaydullin/botkits-board#1]
Название ветки: **Chat-UI-Comp-Vol01**

**ВАЖНО!!! Когда сверстали UI компонент, вносим его в сторибук**

**1. Сообщение (Два состояния отправитель и получатель)** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333852&mode=design&t=XFbciqVCXscSvAxQ-4
**2. Аватар пользователя** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333841&mode=design&t=XFbciqVCXscSvAxQ-4
**3. Кнопка отправить сообщение** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=3509-203485&mode=design&t=XFbciqVCXscSvAxQ-4
**4. Кнопка свернуть правый сайд бар** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333837&mode=design&t=XFbciqVCXscSvAxQ-4
**5. Окно ввода сообщения пользователя** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=3509-203464&mode=design&t=XFbciqVCXscSvAxQ-4

**Comment by seliveren** [comment]
1. ✅
2. ✅
3. ✅
4. ✅
5. ✅

**Comment by lighterboiii** [comment]
@seliveren я сверстал сообщения

**Comment by lighterboiii** [comment]
@AlekseyShaydullin @seliveren можете зайти в ветку Chat-Comp-Talk посмотреть логику и вёрстку, если все ок, то можем мой оставить

**Comment by lighterboiii** [comment]
В сторибук пока не вносил ничего
