### ISSUE TITLE
SAP - Popup Promo

### ISSUE THREAD

**Issue by AlekseyShaydullin** [AlekseyShaydullin/botkits-board#10]
Название ветки: **SAP-Comp-PopupPromo**

**Создать Popup для активации промо кода** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1440-201398&mode=design&t=XFbciqVCXscSvAxQ-4

**Comment by RUS29TAM** [comment]
Сделано [в этом PR](https://github.com/MrStnr21/botkits-14-frontend/pull/107) @AlekseyShaydullin
