### ISSUE TITLE
Chat - Добавить Иконки компонента Vol.1

### ISSUE THREAD

**Issue by AlekseyShaydullin** [AlekseyShaydullin/botkits-board#2]
Название ветки: **Chat-Icons-Vol01**

**ВАЖНО!!! Когда завели иконку, вносим ее в сторибук**

**1. Поиск** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333800&mode=design&t=XFbciqVCXscSvAxQ-4
**2. Фильтр** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333804&mode=design&t=XFbciqVCXscSvAxQ-4
**3. Play** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333897&mode=design&t=XFbciqVCXscSvAxQ-4
**4. Корзина** (есть в UI компонентах, но нет опасити состояния) - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333834&mode=design&t=XFbciqVCXscSvAxQ-4
**5. Иконка Botkits синяя** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-333887&mode=design&t=XFbciqVCXscSvAxQ-4
**6. Скрепка** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=381-15&mode=design&t=XFbciqVCXscSvAxQ-4
**7. Emoji** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=382-5&mode=design&t=XFbciqVCXscSvAxQ-4
**8. Добавить (крестик)** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=713-7103&mode=design&t=XFbciqVCXscSvAxQ-4
**9. Загруженный файл** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1905-334064&mode=design&t=XFbciqVCXscSvAxQ-4
**10. Невидимое сообщение** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1881-334900&mode=design&t=XFbciqVCXscSvAxQ-4

**Comment by seliveren** [comment]
1. ✅
2. ✅
3. ✅
4. ✅
5. ✅
6. ✅
7. ✅
8. ✅
9. ✅
10. ✅
