### ISSUE TITLE
SAP - PaymentPopup

### ISSUE THREAD

**Issue by AlekseyShaydullin** [AlekseyShaydullin/botkits-board#9]
Название ветки: **SAP-Comp-PopupPayment**

**Сверстать Popup** - https://www.figma.com/file/89caTZSLaLwqYKSWH4SXLo/BOTkit-Admin-panel-(Copy-07.08.23)?type=design&node-id=1440-201493&mode=design&t=XFbciqVCXscSvAxQ-4

**Comment by RUS29TAM** [comment]
[PR](https://github.com/MrStnr21/botkits-14-frontend/pull/100) @AlekseyShaydullin
